apiVersion: v1
kind: Pod
metadata:
  name: trafgen-sender
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
  nodeName: cloud0twuttge
