apiVersion: v1
kind: Pod
metadata:
  name: tcpdump
spec:
  containers:
    - name: tcpdump
      image: nicolaka/netshoot
      command: ["tcpdump", "-i", "any", "udp"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
  nodeName: cloud1twuttge